WITH EMPLOYEE_SCORES AS (
    SELECT
        g.EMP_NO,
        SUM(g.SCORE) AS SCORE
    FROM HR_GRADE g
    WHERE g.YEAR = 2022
    GROUP BY g.EMP_NO
)
SELECT
    es.SCORE,
    e.EMP_NO,
    e.EMP_NAME,
    e.POSITION,
    e.EMAIL
FROM EMPLOYEE_SCORES es
JOIN HR_EMPLOYEES e ON es.EMP_NO = e.EMP_NO
WHERE es.SCORE = (SELECT MAX(SCORE) FROM EMPLOYEE_SCORES)
ORDER BY e.EMP_NO;
